// ======================================================================
// \title  DoomSatTopology.cpp
// \brief cpp file containing the topology instantiation code
//
// Generated by `fprime-util new --deployment` (F´ v4.3.0 template) and edited for DoomSat:
// the base clock runs at 20 Hz (50 ms) so the payload poll and TM frame flush are prompt.
// ======================================================================
// Provides access to autocoded functions
#include <DoomSat/Top/DoomSatTopologyAc.hpp>

// Necessary project-specified types
#include <Fw/Types/MallocAllocator.hpp>
#include <Fw/Types/String.hpp>
#include <Svc/Subtopologies/ComCcsds/ComCcsdsConfig/FppConstantsAc.hpp>

#include <cstdlib>

// Allows easy reference to objects in FPP/autocoder required namespaces
using namespace DoomSat;

// The reference topology uses a malloc/free memory manager for buffer allocations
Fw::MallocAllocator mallocator;

// Rate group timing: base clock interval and divisors are coupled to rate group names
const Fw::TimeInterval rateGroupInterval(0, 50000);  // 20Hz base clock (50 ms)
Svc::RateGroupDriver::DividerSet rateGroupDivisorsSet{{{1, 0}, {20, 0}, {80, 0}}};
// Divisors: 20Hz, 1Hz, 0.25Hz

// Context tokens for rate group members (unused, set to zero)
Svc::ActiveRateGroup::ContextArray rateGroup_20HzContext(0);
Svc::ActiveRateGroup::ContextArray rateGroup_1HzContext(0);
Svc::ActiveRateGroup::ContextArray rateGroup_0_25HzContext(0);

enum TopologyConstants {
    COMM_PRIORITY = 34,
    CFDP_FILE_IN_QUEUE_DEPTH = 10,   // fileIn (DpCatalog) requests waiting for the next run1Hz
    CFDP_BUFFER_MANAGER_ID = 400,    // distinct from commsBufferManager (200) and dpBufferManager (300)
    CFDP_BUFFER_SIZE = 1024,         // >= CfdpCfg MaxPduSize + 2-byte packet descriptor
    // >= one channel's per-cycle PDU limit (max_outgoing_pdus_per_cycle 64) and <= ComQueue's FILE depth (100), so
    // a full pool can never overflow that queue. With both channels sending (128 a cycle) channel 1 gets the other
    // 32 and logs BuffersExhausted; it slows down, nothing is lost.
    CFDP_BUFFER_COUNT = 96,
};
static_assert(CFDP_BUFFER_COUNT <= ComCcsdsConfig::QueueDepths::file,
              "cfdpManager's pool must not hold more PDUs than ComQueue's FILE queue");

/**
 * \brief configure/setup components in project-specific way
 */
void configureTopology() {
    // Rate group driver needs a divisor list
    rateGroupDriver.configure(rateGroupDivisorsSet);

    // Rate groups require context arrays.
    rateGroup_20Hz.configure(rateGroup_20HzContext);
    rateGroup_1Hz.configure(rateGroup_1HzContext);
    rateGroup_0_25Hz.configure(rateGroup_0_25HzContext);

    // Command sequencer needs to allocate memory to hold contents of command sequences
    cmdSeq.allocateBuffer(0, mallocator, 5 * 1024);

    // Parameter database: $DOOMSAT_HOME/run/PrmDb.dat, which scripts/wsl_run_flight.sh builds from
    // flight/config/PrmDb.json before each start. Not a relative name: that resolves to the binary's directory
    // (the launchers run it from bin/), and a second file there stops fprime-gds from finding the binary.
    const char* const home = std::getenv("DOOMSAT_HOME");
    const char* const user = std::getenv("HOME");
    Fw::String prmFile;
    if (home != nullptr && home[0] != '\0') {
        prmFile.format("%s/run/PrmDb.dat", home);
    } else {
        prmFile.format("%s/doom/run/PrmDb.dat", (user != nullptr) ? user : "");
    }
    prmDb.configure(prmFile.toChar());  // copies the name

    // CFDP engine (transaction pools, chunk lists, histories) comes from the heap, plus the fileIn handoff queue
    cfdpManager.configure(mallocator, CFDP_FILE_IN_QUEUE_DEPTH);

    // Dedicated PDU buffer pool for cfdpManager
    Svc::BufferManager::BufferBins cfdpBins;
    memset(&cfdpBins, 0, sizeof(cfdpBins));
    cfdpBins.bins[0].bufferSize = CFDP_BUFFER_SIZE;
    cfdpBins.bins[0].numBuffers = CFDP_BUFFER_COUNT;
    cfdpBufferManager.setup(CFDP_BUFFER_MANAGER_ID, 0, mallocator, cfdpBins);
}

// Public functions for use in main program are namespaced with deployment name DoomSat
namespace DoomSat {
void setupTopology(const TopologyState& state) {
    // Autocoded initialization. Function provided by autocoder.
    initComponents(state);
    // Autocoded id setup. Function provided by autocoder.
    setBaseIds();
    // Autocoded connection wiring. Function provided by autocoder.
    connectComponents();
    // Autocoded command registration. Function provided by autocoder.
    regCommands();
    // Autocoded configuration. Function provided by autocoder.
    configComponents(state);
    // Configure the communications driver
    if (state.hostname != nullptr && state.port != 0) {
        comDriver.configure(state.hostname, state.port);
    }
    // Project-specific component configuration. Function provided above. May be inlined, if desired.
    configureTopology();
    // Autocoded parameter read from file. Function provided by autocoder.
    readParameters();
    // Autocoded parameter loading. Function provided by autocoder.
    loadParameters();
    // Autocoded task kick-off (active components). Function provided by autocoder.
    startTasks(state);
    // Initialize communication driver
    if (state.hostname != nullptr && state.port != 0) {
        Os::TaskString name("ReceiveTask");
        // Uplink is configured for receive so a socket task is started
        comDriver.start(name, COMM_PRIORITY, Default::STACK_SIZE);
    }
}

void startRateGroups() {
    // Blocks until stopRateGroups() is called (e.g. from signal handler)
    timer.startTimer(rateGroupInterval);
}

void stopRateGroups() {
    timer.quit();
}

void teardownTopology(const TopologyState& state) {
    // Autocoded (active component) task clean-up. Functions provided by topology autocoder.
    stopTasks(state);
    freeThreads(state);

    // Other task clean-up.
    comDriver.stop();
    (void)comDriver.join();

    // Resource deallocation
    cmdSeq.deallocateBuffer(mallocator);
    cfdpManager.cleanup();
    cfdpBufferManager.cleanup();
    tearDownComponents(state);
    deinitComponents(state);
}
};  // namespace DoomSat
